# Generated by Django 2.0.3 on 2019-06-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('DateShared', models.DateTimeField()),
                ('Thumbnail', models.CharField(max_length=50)),
                ('AccessCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('DocID', models.CharField(max_length=50)),
                ('DateShared', models.DateTimeField()),
                ('OpenNumber', models.IntegerField()),
                ('ServiceType', models.CharField(max_length=30, null=True)),
                ('IconUrl', models.CharField(max_length=100, null=True)),
                ('Url', models.CharField(max_length=100, null=True)),
                ('Collection', models.ManyToManyField(to='users.Collection')),
                ('DocType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='ExtResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('WebAddress', models.CharField(max_length=100)),
                ('DateShared', models.DateTimeField()),
                ('AccessCount', models.IntegerField()),
                ('Collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Collection')),
                ('DocType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DocType')),
            ],
        ),
        migrations.CreateModel(
            name='General_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GradeTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TriggerWord', models.CharField(max_length=30)),
                ('Grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupLabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50, null=True)),
                ('Have_standard', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SharedCollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SharedDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard_Number', models.CharField(max_length=50)),
                ('Strand', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='StandardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetLabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=30)),
                ('StateAbbr', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StateStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StandardSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StandardSet')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.State')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Population', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TriggerWord', models.CharField(max_length=30)),
                ('Subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30, null=True)),
                ('Lastname', models.CharField(max_length=30, null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('GmailID', models.CharField(max_length=50)),
                ('General_Tags', models.ManyToManyField(to='users.General_Tag')),
                ('Grades', models.ManyToManyField(to='users.Grade')),
                ('Group', models.ManyToManyField(to='users.Group')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Role')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.School')),
                ('Student_needs', models.ManyToManyField(to='users.Student_Need')),
                ('Subjects', models.ManyToManyField(to='users.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='statestandard',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
        ),
        migrations.AddField(
            model_name='standard',
            name='StandardSet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.StandardSet'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='SharedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='sharedcollection',
            name='SharedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='school',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.State'),
        ),
        migrations.AddField(
            model_name='extresource',
            name='General_Tags',
            field=models.ManyToManyField(to='users.General_Tag'),
        ),
        migrations.AddField(
            model_name='extresource',
            name='Grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Grade'),
        ),
        migrations.AddField(
            model_name='extresource',
            name='Owner_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='extresource',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
        ),
        migrations.AddField(
            model_name='document',
            name='General_Tags',
            field=models.ManyToManyField(to='users.General_Tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='Grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Grade'),
        ),
        migrations.AddField(
            model_name='document',
            name='Owner_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='document',
            name='Standard',
            field=models.ManyToManyField(to='users.Standard'),
        ),
        migrations.AddField(
            model_name='document',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
        ),
        migrations.AddField(
            model_name='collection',
            name='Owner_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
