# Generated by Django 2.0.3 on 2019-06-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190615_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
