# Generated by Django 2.0.3 on 2019-06-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_collection_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
