# Generated by Django 2.0.3 on 2019-06-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='grade_triggerword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.GradeTrigger'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject_triggerword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubjectTrigger'),
        ),
    ]
