# Generated by Django 2.0.3 on 2019-06-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190623_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=50)),
                ('parent_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('memeber_since_date', models.DateTimeField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Community')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='communitymemeber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='community',
            field=models.ManyToManyField(to='users.Community'),
        ),
    ]
