# Generated by Django 2.0.3 on 2019-06-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_community_parent_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='community',
            new_name='shared_community',
        ),
    ]
