# Generated by Django 2.0.3 on 2019-06-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190629_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityMemeber',
            new_name='CommunityMember',
        ),
    ]
