# Generated by Django 2.0.3 on 2019-06-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190629_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymember',
            old_name='memeber_since_date',
            new_name='member_since_date',
        ),
    ]
