# Generated by Django 2.0.3 on 2019-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='StateAbbr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
