# Generated by Django 2.0.3 on 2019-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190702_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Have_standard',
            field=models.IntegerField(),
        ),
    ]
