# Generated by Django 2.0.3 on 2019-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190702_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='statestandard',
            name='Category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
