# Generated by Django 2.0.3 on 2019-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_communityuseremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GradeTrigger',
            field=models.ManyToManyField(to='users.GradeTrigger'),
        ),
    ]
