# Generated by Django 2.0.3 on 2019-07-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_gradetrigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardset',
            name='SetLabel',
            field=models.CharField(max_length=100),
        ),
    ]
