from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('register/', views.register),
    path('token/', views.token),
    path('token/refresh/', views.refresh_token),
    path('token/revoke/', views.revoke_token),
    path('login/', views.login),
    path('basedata/', views.basedata),
    path('cordata/', views.cordata),
    path('get_strand/', views.getStrand),
    path('get_standard/', views.getStandard),
    path('upload_file/', views.uploadFile),
    path('searchdata/', views.searchData),
    path('getmydata/', views.getMyData),
    path('collectiondata/', views.getCollectiondata),
    path('collection_detail/', views.getCollectionDetail),
    path('collection_share/', views.collectionShare),
    path('collection_detail_from_uuid/', views.getCollectionDetailFromUUID),
    path('change-collection-title-description', views.changeCollectionTitleDescription),
    path('create-empty-collection', views.createEmptyCollection),
    path('remove-document', views.removeDocument),
    path('remove-collection', views.removeCollection),
    path('remove-shared-collection', views.remove_shared_collection),
    path('get-web-thumbnail', views.getWebThumbnail),
    path('search-collection', views.searchCollection),
    path('get-document-data', views.getDocumentData),
    path('update-file', views.updateFile),
    path('get-community', views.get_community),
    path('get-admin-communities', views.get_admin_communities),
    path('save-sharing-setting', views.save_sharings_setting),
    path('is-admin', views.is_admin),
    path('get-users-per-communities', views.get_users_per_communities),
    path('save-community-setting', views.save_community_setting),
    path('get-webimage-by-random-number', views.get_webimage_by_random_number),
    path('search-school', views.search_school),
    path('get-community-name', views.get_community_name),
    path('add-email-to-community', views.add_email_to_community),
    path('add-email-from-csv', views.add_email_from_csv),
    path('download-csv', views.download_csv),
    path('get-profile-data', views.get_profile_data),
    path('update-profile', views.update_profile),
] 